create table TAXLOAN_APPLY
(
  apply_id                      NUMBER(20) not null,
  org_code                      VARCHAR2(20) not null,
  mer_id                        NUMBER,
  apply_no                      VARCHAR2(40),
  cert_type                     VARCHAR2(1),
  cert_code                     VARCHAR2(20),
  cust_name                     VARCHAR2(60),
  cert_org                      VARCHAR2(62),
  rel_addr                      VARCHAR2(300),
  rel_post_code                 VARCHAR2(6),
  email                         VARCHAR2(60),
  cust_mobile                   VARCHAR2(15),
  edu_level                     VARCHAR2(1),
  live_status                   VARCHAR2(1),
  live_addr                     VARCHAR2(186),
  live_post_code                VARCHAR2(6),
  marr_status                   VARCHAR2(2),
  spouse_name                   VARCHAR2(60),
  spouse_cert_type              VARCHAR2(1),
  spouse_cert_code              VARCHAR2(20),
  cust_mobile_real              VARCHAR2(15),
  loan_purpose                  VARCHAR2(1) default '1',
  repay_bank_name               VARCHAR2(100),
  repay_acc_no                  VARCHAR2(20),
  inner_apply_status            VARCHAR2(2) default '00',
  tax_data                      VARCHAR2(1),
  create_time                   DATE,
  update_time                   DATE,
  appoint_time                  DATE,
  org_rule_filepath             VARCHAR2(200),
  org_capital_report_filepath   VARCHAR2(200),
  org_financial_report_filepath VARCHAR2(200),
  org_tax_dec_filepath          VARCHAR2(200),
  org_credit_report_filepath    VARCHAR2(200),
  org_bank_statement_filepath   VARCHAR2(200),
  remark1                       VARCHAR2(200),
  remark2                       VARCHAR2(200),
  remark3                       VARCHAR2(200),
  remark4                       VARCHAR2(200),
  mer_apply_status              VARCHAR2(2) default '00',
  mer_apply_user                VARCHAR2(100),
  inner_apply_user              VARCHAR2(100),
  mer_apply_time                DATE,
  inner_apply_time              DATE,
  inner_apply_desc              VARCHAR2(200),
  mer_apply_desc                VARCHAR2(200)
)

create table TAXLOAN_ORDER
(
  id               NUMBER not null,
  order_no         VARCHAR2(30),
  apply_id         NUMBER(20),
  mer_contr_no     NUMBER(20),
  org_code         VARCHAR2(20),
  user_id          NUMBER,
  order_amt        VARCHAR2(17),
  order_total_fee  VARCHAR2(17),
  order_status     VARCHAR2(2),
  fee_status       VARCHAR2(2),
  order_rate       VARCHAR2(17),
  eplat_fee_amt    VARCHAR2(17),
  eplat_fee_rate   VARCHAR2(17),
  mer_fee_amt      VARCHAR2(17),
  mer_fee_rate     VARCHAR2(17),
  gua_info         VARCHAR2(100),
  repay_type       VARCHAR2(2),
  rec_status       VARCHAR2(1),
  fk_upload_status VARCHAR2(1),
  create_time      DATE,
  update_time      DATE,
  mer_input_time   DATE,
  eplat_input_time DATE,
  repay_time       DATE
)


create table TAXLOAN_ORG_DATAMONTH
(
  id         NUMBER not null,
  org_code   VARCHAR2(18),
  data_month VARCHAR2(12),
  sum_cnt    VARCHAR2(10),
  sum_sum    VARCHAR2(15)
)

-- Create table
create table PEPP_FRM.SMC_ORG
(
  org_id                    NUMBER(20) not null,
  org_code                  VARCHAR2(100),
  org_customs_code          VARCHAR2(100),
  master_customs_code       VARCHAR2(32),
  org_name                  VARCHAR2(128) not null,
  short_name                VARCHAR2(128),
  eng_name                  VARCHAR2(128),
  reg_country               VARCHAR2(5),
  loc_country               VARCHAR2(5),
  agrt_no                   VARCHAR2(32),
  corporation               VARCHAR2(64),
  zip                       VARCHAR2(32),
  address                   VARCHAR2(255),
  fax                       VARCHAR2(64),
  linkman                   VARCHAR2(64),
  phone                     VARCHAR2(32),
  email                     VARCHAR2(64),
  create_time               DATE,
  update_time               DATE,
  org_type                  VARCHAR2(2),
  taxy_reg_no               VARCHAR2(100),
  title                     VARCHAR2(32),
  status                    VARCHAR2(1) default 1,
  supplement1               VARCHAR2(256),
  supplement2               VARCHAR2(256),
  supplement3               VARCHAR2(256),
  customer_code             VARCHAR2(16),
  duty_scope                VARCHAR2(512),
  duty_type                 VARCHAR2(128),
  lawman                    VARCHAR2(100),
  lawman_passtype           VARCHAR2(4),
  lawman_passcode           VARCHAR2(256),
  duty_license              BLOB,
  org_license               BLOB,
  audit_user                VARCHAR2(100),
  taxy_reg_license          BLOB,
  law_man_license           BLOB,
  approvaled_status         VARCHAR2(1) default '0',
  approvaled_notes          VARCHAR2(32),
  approvaled_date           DATE,
  license                   VARCHAR2(255),
  org_license_file          VARCHAR2(255),
  taxy_reg_license_file     VARCHAR2(255),
  lawman_idcode_up          VARCHAR2(255),
  eims_sync_flag            VARCHAR2(1) default 2,
  from_sys_code             VARCHAR2(10) default 'EPLAT00',
  belong_custom_code        VARCHAR2(32),
  ebs_org_name              VARCHAR2(128),
  ebs_taxy_reg_no           VARCHAR2(100),
  ebs_org_phone             VARCHAR2(100),
  ebs_org_account           VARCHAR2(255),
  ebs_tax_payer             NUMBER(1),
  reg_address               VARCHAR2(255),
  mobile_phone              VARCHAR2(100),
  ebs_org_branch            VARCHAR2(255),
  update_user_name          VARCHAR2(64),
  update_user_type          VARCHAR2(10),
  update_user_id            NUMBER(20),
  ebs_update_time           DATE default to_date('2012-08-01','YYYY-MM-DD'),
  actuld_protocol_scanner1  VARCHAR2(64),
  actuld_protocol_scanner2  VARCHAR2(64),
  actuld_protocol_scanner3  VARCHAR2(64),
  actuld_protocol_scanner4  VARCHAR2(64),
  actuld_other_proof1       VARCHAR2(64),
  actuld_other_proof2       VARCHAR2(64),
  actuld_other_proof3       VARCHAR2(64),
  actuld_other_proof4       VARCHAR2(64),
  actuld_protocol_scanner5  VARCHAR2(64),
  actuld_protocol_scanner6  VARCHAR2(64),
  actuld_other_proof5       VARCHAR2(64),
  actuld_other_proof6       VARCHAR2(64),
  credit_code               VARCHAR2(64),
  province                  VARCHAR2(64),
  city                      VARCHAR2(64),
  licence_start_time        DATE,
  lawman_idcode_start_time  DATE,
  licence_finish_time       DATE,
  lawman_idcode_finish_time DATE,
  check_result              VARCHAR2(12),
  lawman_idcode_con         VARCHAR2(255),
  realname_other_proof1     VARCHAR2(64),
  realname_other_proof2     VARCHAR2(64),
  realname_other_proof3     VARCHAR2(64),
  realname_other_proof4     VARCHAR2(64),
  realname_other_proof5     VARCHAR2(64),
  realname_other_proof6     VARCHAR2(64),
  realname_other_proof7     VARCHAR2(64),
  realname_other_proof8     VARCHAR2(64),
  realname_other_proof9     VARCHAR2(64),
  duty_license_file         VARCHAR2(255),
  law_man_license_file      VARCHAR2(255),
  step                      VARCHAR2(32) default 1 not null,
  is_card_org               VARCHAR2(2) default 0,
  des_flag                  NUMBER default 0,
  capital                   NUMBER(16,2) default 0,
  agent_user_name           VARCHAR2(32),
  agent_user_cellphone      VARCHAR2(11),
  agent_user_email          VARCHAR2(32),
  agent_user_idcode_up      VARCHAR2(255),
  agent_user_idcode_con     VARCHAR2(255),
  branch_open_file          VARCHAR2(255),
  agent_id_code             VARCHAR2(32),
  agent_id_type             VARCHAR2(2) default 01,
  agent_id_start_time       DATE,
  agent_id_end_time         DATE,
  org_score_syncdata_time   DATE,
  org_score_time            DATE,
  org_score                 NUMBER(22,2),
  org_score_desc            VARCHAR2(2000),
  org_level                 VARCHAR2(1),
  is_score                  NUMBER(1) default '0',
  b2b_type                  VARCHAR2(2),
  final_approval_apply_time DATE,
  last_patch_time           DATE
)